p8105\_hw5
================
Ruilian Zhang
11/12/2021

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

``` r
homicide_df = read_csv("data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = ", "))
```

    ## Rows: 52179 Columns: 12

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
n_homicides_df = homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    n_homicides = n()
  )

n_unsolved_df = homicide_df %>% 
  group_by(city_state) %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  summarize(
    n_unsolved = n()
  )

left_join(n_homicides_df, n_unsolved_df, by = "city_state") %>% 
  mutate(n_unsolved = replace_na(n_unsolved, 0)) %>% 
  knitr::kable()
```

| city\_state        | n\_homicides | n\_unsolved |
|:-------------------|-------------:|------------:|
| Albuquerque, NM    |          378 |         146 |
| Atlanta, GA        |          973 |         373 |
| Baltimore, MD      |         2827 |        1825 |
| Baton Rouge, LA    |          424 |         196 |
| Birmingham, AL     |          800 |         347 |
| Boston, MA         |          614 |         310 |
| Buffalo, NY        |          521 |         319 |
| Charlotte, NC      |          687 |         206 |
| Chicago, IL        |         5535 |        4073 |
| Cincinnati, OH     |          694 |         309 |
| Columbus, OH       |         1084 |         575 |
| Dallas, TX         |         1567 |         754 |
| Denver, CO         |          312 |         169 |
| Detroit, MI        |         2519 |        1482 |
| Durham, NC         |          276 |         101 |
| Fort Worth, TX     |          549 |         255 |
| Fresno, CA         |          487 |         169 |
| Houston, TX        |         2942 |        1493 |
| Indianapolis, IN   |         1322 |         594 |
| Jacksonville, FL   |         1168 |         597 |
| Kansas City, MO    |         1190 |         486 |
| Las Vegas, NV      |         1381 |         572 |
| Long Beach, CA     |          378 |         156 |
| Los Angeles, CA    |         2257 |        1106 |
| Louisville, KY     |          576 |         261 |
| Memphis, TN        |         1514 |         483 |
| Miami, FL          |          744 |         450 |
| Milwaukee, wI      |         1115 |         403 |
| Minneapolis, MN    |          366 |         187 |
| Nashville, TN      |          767 |         278 |
| New Orleans, LA    |         1434 |         930 |
| New York, NY       |          627 |         243 |
| Oakland, CA        |          947 |         508 |
| Oklahoma City, OK  |          672 |         326 |
| Omaha, NE          |          409 |         169 |
| Philadelphia, PA   |         3037 |        1360 |
| Phoenix, AZ        |          914 |         504 |
| Pittsburgh, PA     |          631 |         337 |
| Richmond, VA       |          429 |         113 |
| Sacramento, CA     |          376 |         139 |
| San Antonio, TX    |          833 |         357 |
| San Bernardino, CA |          275 |         170 |
| San Diego, CA      |          461 |         175 |
| San Francisco, CA  |          663 |         336 |
| Savannah, GA       |          246 |         115 |
| St. Louis, MO      |         1677 |         905 |
| Stockton, CA       |          444 |         266 |
| Tampa, FL          |          208 |          95 |
| Tulsa, AL          |            1 |           0 |
| Tulsa, OK          |          583 |         193 |
| Washington, DC     |         1345 |         589 |

``` r
baltimore_prop = prop.test(c(1825, 1002), n = c(2827, 2827), alternative = "two.sided")

baltimore_prop_tidy = broom::tidy(baltimore_prop, conf.int = TRUE)

pull(baltimore_prop_tidy, estimate1)
```

    ## [1] 0.6455607

``` r
c(pull(baltimore_prop_tidy, conf.low), pull(baltimore_prop_tidy, conf.high))
```

    ## [1] 0.2658309 0.3164118

For unsolved homicides in Baltimore, the estimated proportion is
0.6455607. The confidence interval is (0.2658309, 0.3164118).
