---
title: "p8105_hw5"
author: "Ruilian Zhang"
date: "11/12/2021"
output: github_document
---

```{r}
library(tidyverse)
```


## Problem 1

```{r import and summary data}
homicide_df = read_csv("data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = ", "))

n_homicides_df = homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    n_homicides = n()
  )

n_unsolved_df = homicide_df %>% 
  group_by(city_state) %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  summarize(
    n_unsolved = n()
  )

city_summary_df = left_join(n_homicides_df, n_unsolved_df, by = "city_state") %>% 
  mutate(n_unsolved = replace_na(n_unsolved, 0))

knitr::kable(city_summary_df)
```

```{r prop test baltimore}
baltimore_prop = prop.test(x = c(1825, 1002), n = c(2827, 2827), alternative = "two.sided")

baltimore_prop_tidy = broom::tidy(baltimore_prop, conf.int = TRUE)

pull(baltimore_prop_tidy, estimate1)
c(pull(baltimore_prop_tidy, conf.low), pull(baltimore_prop_tidy, conf.high))
```

* For unsolved homicides in Baltimore, the estimated proportion is `r pull(baltimore_prop_tidy, estimate1)`. The confidence interval is (`r c(pull(baltimore_prop_tidy, conf.low), pull(baltimore_prop_tidy, conf.high))`).

```{r proptest each city}
city_summary_nested = nest(city_summary_df, data = c("n_homicides", "n_unsolved"))

city_prop = function(df) {
  
  n = df[[1]]
  n1 = df[[2]]
  n2 = n - n1
  
  prop_test = prop.test(c(n1, n2), c(n, n), alternative = "two.sided") %>% 
    broom::tidy(conf.int = TRUE)
  
  tibble(
    unsolved_prop = round(pull(prop_test, estimate1), 2),
    conf_int = str_c(round(pull(prop_test, conf.low), 2),  round(pull(prop_test, conf.high), 2), sep = ", ")
    )
    
  }

city_summary_nested %>% 
  mutate(prop_results = map(data, city_prop)) %>% 
  unnest(prop_results) %>% 
  select(-data) %>% 
  knitr::kable()
```

